from PyQt6.QtWidgets import QWidget, QVBoxLayout, QLabel, QPushButton, QSpacerItem, QSizePolicy
from PyQt6.QtCore import Qt

class WelcomePage(QWidget):
    def __init__(self, on_start, on_admin):
        super().__init__()
        layout = QVBoxLayout(self)
        layout.setAlignment(Qt.AlignmentFlag.AlignCenter)
        layout.setSpacing(20)
        layout.addSpacerItem(QSpacerItem(20, 60, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding))
        title = QLabel("Система підтримки прийняття рішень")
        title.setObjectName("titleLabel")
        title.setAlignment(Qt.AlignmentFlag.AlignCenter)
        layout.addWidget(title)
        subtitle = QLabel("Підбір резервного живлення для дому")
        subtitle.setObjectName("subtitleLabel")
        subtitle.setAlignment(Qt.AlignmentFlag.AlignCenter)
        layout.addWidget(subtitle)
        desc = QLabel("Дайте відповіді на запитання, і система\nпідбере оптимальне рішення для вашого випадку.")
        desc.setAlignment(Qt.AlignmentFlag.AlignCenter)
        desc.setStyleSheet("font-size: 14px; color: #a0a0b0;")
        layout.addWidget(desc)
        btn_start = QPushButton("Почати консультацію")
        btn_start.setObjectName("btnPrimary")
        btn_start.setFixedWidth(300)
        btn_start.setCursor(Qt.CursorShape.PointingHandCursor)
        btn_start.clicked.connect(on_start)
        layout.addWidget(btn_start, alignment=Qt.AlignmentFlag.AlignCenter)
        btn_admin = QPushButton("Панель адміністратора")
        btn_admin.setFixedWidth(300)
        btn_admin.setCursor(Qt.CursorShape.PointingHandCursor)
        btn_admin.clicked.connect(on_admin)
        layout.addWidget(btn_admin, alignment=Qt.AlignmentFlag.AlignCenter)
        layout.addSpacerItem(QSpacerItem(20, 60, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding))
